---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Cell In[50], line 1
----> 1 model.fit(train, validation_data=test, epochs=100, callbacks=[checkpoint_callback, schedule_callback, example_callback])

File ~/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File ~/Downloads/lipnet/myenv/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51 try:
     52   ctx.ensure_initialized()
---> 53   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                       inputs, attrs, num_outputs)
     55 except core._NotOkStatusException as e:
     56   if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node sequential_1/time_distributed_1/Reshape defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code

  File "/tmp/ipykernel_4445/3536403359.py", line 1, in <module>

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 318, in fit

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 121, in one_step_on_iterator

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 108, in one_step_on_data

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 51, in train_step

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 882, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/models/sequential.py", line 209, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/models/functional.py", line 175, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/function.py", line 171, in _run_through_graph

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/models/functional.py", line 556, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 882, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/rnn/time_distributed.py", line 108, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/rnn/time_distributed.py", line 108, in <listcomp>

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/rnn/time_distributed.py", line 102, in step_function

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py", line 54, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/numpy.py", line 4440, in reshape

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/numpy.py", line 1789, in reshape

Detected at node sequential_1/time_distributed_1/Reshape defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code

  File "/tmp/ipykernel_4445/3536403359.py", line 1, in <module>

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 318, in fit

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 121, in one_step_on_iterator

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 108, in one_step_on_data

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 51, in train_step

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 882, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/models/sequential.py", line 209, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/models/functional.py", line 175, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/function.py", line 171, in _run_through_graph

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/models/functional.py", line 556, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/layer.py", line 882, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/operation.py", line 46, in __call__

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/rnn/time_distributed.py", line 108, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/rnn/time_distributed.py", line 108, in <listcomp>

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/rnn/time_distributed.py", line 102, in step_function

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py", line 54, in call

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/ops/numpy.py", line 4440, in reshape

  File "/home/kbc/Downloads/lipnet/myenv/lib/python3.10/site-packages/keras/src/backend/tensorflow/numpy.py", line 1789, in reshape

2 root error(s) found.
  (0) INVALID_ARGUMENT:  Only one input size may be -1, not both 0 and 1
	 [[{{node sequential_1/time_distributed_1/Reshape}}]]
	 [[StatefulPartitionedCall/compile_loss/ctc_loss/Log/_72]]
  (1) INVALID_ARGUMENT:  Only one input size may be -1, not both 0 and 1
	 [[{{node sequential_1/time_distributed_1/Reshape}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_one_step_on_iterator_28550]
